"""added experience column to employee table

Revision ID: 8472fb37c02e
Revises: 
Create Date: 2024-06-27 15:49:21.957825

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8472fb37c02e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audits')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('experience', sa.String(length=255), nullable=True))
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('department',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('department',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('experience')

    op.create_table('audits',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('msg', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
